# Generated by Django 4.2.26 on 2025-11-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('days_after_pruning', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Grapes, Pomegranate', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Thompson Seedless, Sonaka', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='assign.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Varieties',
                'ordering': ['name'],
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('village', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_size_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('farmer_price_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workers_needed', models.IntegerField(default=5, help_text='Number of workers required for this job')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('assigned', 'Assigned to Mukadams'), ('bidding', 'Receiving Bids'), ('finalized', 'Mukadam Finalized'), ('in_progress', 'Work in Progress'), ('priced', 'Priced'), ('notified', 'Notified'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('your_price_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finalized_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.activity')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='Mukadam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('number_of_labourers', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fcm_token', models.CharField(blank=True, help_text='Firebase token for push notifications', max_length=255, null=True)),
                ('fcm_token_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(max_length=20)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='assign.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assign.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_by', models.CharField(max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('assign_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='assign.job')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assign.job')),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.mukadam')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_mukadam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='assign.mukadam'),
        ),
        migrations.AddField(
            model_name='job',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assign.crop'),
        ),
        migrations.AddField(
            model_name='job',
            name='crop_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assign.cropvariety'),
        ),
        migrations.AddField(
            model_name='job',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.farmer'),
        ),
        migrations.AddField(
            model_name='job',
            name='finalized_mukadam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_jobs', to='assign.mukadam'),
        ),
        migrations.CreateModel(
            name='FarmerPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('activity_name', models.CharField(blank=True, help_text='Legacy field - e.g., SSN, Anushka', max_length=200)),
                ('pruning_date', models.DateField(help_text='Actual pruning date')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, help_text='Linked activity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assign.activity')),
                ('crop', models.ForeignKey(blank=True, help_text='Type of crop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assign.crop')),
                ('crop_variety', models.ForeignKey(blank=True, help_text='Variety of crop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assign.cropvariety')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='assign.farmer')),
            ],
            options={
                'ordering': ['-pruning_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmerEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_by', models.CharField(max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('model_name', models.CharField(default='Farmer', max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='assign.farmer')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MukadamInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_interested', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('declined', 'Declined'), ('assigned', 'Assigned')], default='pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='assign.job')),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.mukadam')),
            ],
            options={
                'unique_together': {('job', 'mukadam')},
            },
        ),
        migrations.CreateModel(
            name='MukadamBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('declined', 'Declined'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bid_price_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_hours', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='assign.job')),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.mukadam')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'mukadam')},
            },
        ),
        migrations.CreateModel(
            name='MukadamActivityRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.activity')),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rates', to='assign.mukadam')),
            ],
            options={
                'ordering': ['activity__name'],
                'unique_together': {('mukadam', 'activity')},
            },
        ),
    ]
