# Generated by Django 4.2.26 on 2025-11-18 06:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_activity_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MukadamUnavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(help_text='e.g., Personal leave, Holiday', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to='assign.mukadam')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
