# Generated by Django 4.2.26 on 2025-11-18 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_mukadamunavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MukadamAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Any special notes about this availability period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mukadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='assign.mukadam')),
            ],
            options={
                'verbose_name': 'Mukadam Availability',
                'verbose_name_plural': 'Mukadam Availabilities',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='MukadamUnavailability',
        ),
    ]
