# Generated by Django 4.2.26 on 2025-11-18 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_mukadamavailability_delete_mukadamunavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivityRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_per_acre', models.DecimalField(decimal_places=2, help_text='Your rate to pay mukadams', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this rate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rates', to='assign.activity')),
            ],
            options={
                'ordering': ['activity__name'],
                'unique_together': {('activity',)},
            },
        ),
    ]
