# Generated by Django 4.2.26 on 2025-11-20 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mukkadam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mukkadam_name', models.CharField(max_length=255)),
                ('mobile_numbers', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('has_smartphone', models.CharField(max_length=10)),
                ('crew_size', models.CharField(max_length=50)),
                ('max_crew_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('splitting_logic', models.TextField(blank=True, null=True)),
                ('deputy_mukkadam_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deputy_mukkadam_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_work_timing', models.CharField(blank=True, max_length=100)),
                ('team_availabilities', models.JSONField(blank=True, default=list)),
                ('rate_card', models.JSONField(blank=True, default=dict)),
                ('home_location', models.CharField(blank=True, max_length=255)),
                ('preferred_work_locations', models.TextField(blank=True)),
                ('max_travel_distance', models.CharField(blank=True, max_length=50)),
                ('transport_mode', models.CharField(max_length=50)),
                ('transport_arranged_by', models.CharField(blank=True, max_length=50)),
                ('transport_charges', models.JSONField(blank=True, default=dict)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('work_mode', models.CharField(max_length=50)),
                ('move_in_preferred_region', models.CharField(blank=True, max_length=255)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('other_commitments', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='mukkadams/profiles/')),
                ('aadhar_card', models.ImageField(blank=True, null=True, upload_to='mukkadams/aadhar/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='mukkadams/pan/')),
                ('bank_proof', models.ImageField(blank=True, null=True, upload_to='mukkadams/bank/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mukkadams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
