# Generated by Django 4.2.26 on 2025-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mukkadam',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
