# Generated by Django 4.2.26 on 2025-11-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mukkadam',
            name='referral_source_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mukkadam',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='core.mukkadam'),
        ),
    ]
