# Generated by Django 4.2.26 on 2025-11-21 06:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mukkadam_referral_source_text_mukkadam_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukkadam',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='bank_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path),
        ),
    ]
