# Generated by Django 4.2.26 on 2025-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mukkadam_aadhar_card_alter_mukkadam_bank_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukkadam',
            name='daily_work_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
