# Generated by Django 4.2.26 on 2025-11-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mukkadam_daily_work_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukkadam',
            name='max_travel_distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='move_in_preferred_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='referral_source_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mukkadam',
            name='transport_arranged_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
