# Generated by Django 5.2.7 on 2025-10-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
    ]
