# Generated by Django 4.2.7 on 2025-10-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dayrange',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='dayrangeproduct',
            name='application_method',
        ),
        migrations.RemoveField(
            model_name='dayrangeproduct',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
