# Generated by Django 4.2.7 on 2025-10-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_remove_activity_description_remove_crop_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayrange',
            name='tracking_from',
        ),
    ]
