# Generated by Django 4.2.7 on 2025-10-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_remove_dayrange_tracking_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_marathi', models.CharField(max_length=100, verbose_name='औषधाचे नाव')),
                ('name_english', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='उद्देश')),
                ('purpose_english', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purpose')),
                ('eu_mrl', models.CharField(blank=True, max_length=50, null=True, verbose_name='EU एम आर एल')),
                ('phi', models.IntegerField(blank=True, null=True, verbose_name='पी एच आय')),
                ('rate_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='प्रमाण प्रती लि.')),
                ('num_sprays', models.IntegerField(verbose_name='एकूण स्प्रे')),
                ('total_quantity_per_acre', models.CharField(max_length=50, verbose_name='एकूण प्रमाण / एकर')),
                ('spray_days', models.CharField(max_length=200, verbose_name='स्प्रे चा दिवस')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesticide_references', to='calender.cropvariety')),
            ],
            options={
                'verbose_name': 'Pesticide Reference',
                'verbose_name_plural': 'Pesticide References',
                'ordering': ['name_english'],
            },
        ),
    ]
