# Generated by Django 4.2.7 on 2025-10-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_pesticidereference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PesticideReference',
        ),
    ]
