# Generated by Django 5.2.7 on 2025-10-25 11:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_delete_pesticidereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_marathi',
            field=models.TextField(blank=True, help_text='Product description in Marathi', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='S3 URL or path to product image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Is product available in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling Price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product size/quantity', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('liter', 'Liter'), ('piece', 'Piece'), ('pack', 'Pack')], help_text='Unit of measurement for size', max_length=20, null=True),
        ),
    ]
