# Generated by Django 5.2.7 on 2025-10-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_product_description_product_description_marathi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_marathi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
