# Generated by Django 5.2.7 on 2025-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayrange',
            options={},
        ),
        migrations.AlterField(
            model_name='dayrange',
            name='end_day',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dayrange',
            name='start_day',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='dayrange',
            index=models.Index(fields=['crop_variety', 'activity'], name='calender_da_crop_va_9923cb_idx'),
        ),
        migrations.AddIndex(
            model_name='dayrange',
            index=models.Index(fields=['start_day', 'end_day'], name='calender_da_start_d_8f8592_idx'),
        ),
    ]
