# Generated by Django 5.2.7 on 2025-10-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0012_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(choices=[('product', 'Product'), ('crop', 'Crop'), ('variety', 'Crop Variety'), ('activity', 'Activity'), ('dayrange', 'Day Range'), ('dayrange_product', 'Day Range Product')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='calender_au_model_n_7b6806_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='calender_au_timesta_ac7e78_idx'),
        ),
    ]
